In [9]:
import pandas as pd

In [10]:
data = pd.read_csv('C:/Users/parth/Downloads/Activity Recognition from Single Chest-Mounted Accelerometer/Activity Recognition from Single Chest-Mounted Accelerometer/1.csv',header = None, names = ["Index" , "X_ACCELERATION_UNCALIBERATED","Y_ACCELERATION_UNCALIBERATED","Z_ACCELERATION_UNCALIBERATED","labels"])
data.index +=1

In [11]:
data1 = data.drop(['Index','labels'],axis = 1)

In [26]:
s = pd.date_range("00:00", "00:51.50", freq="0.019S",name = ['TIME']).time
t = pd.DataFrame(s,columns = ["HEADER_TIMESTAMP"])
b = t.join(data1, lsuffix='_t', rsuffix='_data1')
a = b.dropna()
#a.to_csv('1_new1.csv',index = False , sep= ',')

In [46]:
def mhealth_format(data):
    data1 = data.drop(['Index','labels'],axis = 1)
    s1 = pd.Series(pd.date_range('20131212',freq='0.019S',periods=162501,name='HEADER_TIMESTAMP'))
    t1 = pd.DataFrame(s1)
    b1 = t1.join(data1, lsuffix='_t', rsuffix='_data1')
    a1 = b1.dropna()
    
    return a1

In [47]:
mhealth_format(data = data)

,HEADER_TIMESTAMP,X_ACCELERATION_UNCALIBERATED,Y_ACCELERATION_UNCALIBERATED,Z_ACCELERATION_UNCALIBERATED
1,2013-12-12 00:00:00.019,1502.0,2215.0,2153.0
2,2013-12-12 00:00:00.038,1667.0,2072.0,2047.0
3,2013-12-12 00:00:00.057,1611.0,1957.0,1906.0
4,2013-12-12 00:00:00.076,1601.0,1939.0,1831.0
5,2013-12-12 00:00:00.095,1643.0,1965.0,1879.0
6,2013-12-12 00:00:00.114,1604.0,1959.0,1921.0
7,2013-12-12 00:00:00.133,1640.0,1829.0,1940.0
8,2013-12-12 00:00:00.152,1607.0,1910.0,1910.0
9,2013-12-12 00:00:00.171,1546.0,2045.0,1910.0
10,2013-12-12 00:00:00.190,1529.0,2049.0,1972.0
11,2013-12-12 00:00:00.209,1637.0,1978.0,1945.0
12,2013-12-12 00:00:00.228,1596.0,2046.0,1866.0
13,2013-12-12 00:00:00.247,1590.0,2006.0,1978.0
14,2013-12-12 00:00:00.266,1601.0,1966.0,1957.0
15,2013-12-12 00:00:00.285,1542.0,2003.0,1959.0
16,2013-12-12 00:00:00.304,1598.0,2027.0,1941.0
17,2013-12-12 00:00:00.323,1511.0,2258.0,1983.0
18,2013-12-12 00:00:00.342,1555.0,1980.0,2023.0
19,2013-12-12 00:00:00.361,1508.0,2468.0,1934.0
20,2013-12-12 00:00:00.380,1580.0,1697.0,2005.0
21,2013-12-12 00:00:00.399,1627.0,2073.0,1992.0
22,2013-12-12 00:00:00.418,1592.0,2130.0,2063.0
23,2013-12-12 00:00:00.437,1634.0,2088.0,1991.0
24,2013-12-12 00:00:00.456,1638.0,2102.0,1916.0
25,2013-12-12 00:00:00.475,1593.0,2123.0,1948.0
26,2013-12-12 00:00:00.494,1542.0,2133.0,2034.0
27,2013-12-12 00:00:00.513,1601.0,2015.0,2042.0
28,2013-12-12 00:00:00.532,1613.0,1938.0,1936.0
29,2013-12-12 00:00:00.551,1644.0,1974.0,2000.0
30,2013-12-12 00:00:00.570,1642.0,1933.0,2046.0
...,...,...,...,...
162471,2013-12-12 00:51:26.949,1925.0,2380.0,2075.0
162472,2013-12-12 00:51:26.968,1923.0,2381.0,2074.0
162473,2013-12-12 00:51:26.987,1926.0,2382.0,2071.0
162474,2013-12-12 00:51:27.006,1924.0,2382.0,2075.0
162475,2013-12-12 00:51:27.025,1923.0,2385.0,2071.0
162476,2013-12-12 00:51:27.044,1921.0,2383.0,2079.0
162477,2013-12-12 00:51:27.063,1924.0,2383.0,2083.0
162478,2013-12-12 00:51:27.082,1925.0,2385.0,2070.0
162479,2013-12-12 00:51:27.101,1932.0,2384.0,2080.0
162480,2013-12-12 00:51:27.120,1924.0,2385.0,2081.0
162481,2013-12-12 00:51:27.139,1930.0,2383.0,2076.0
162482,2013-12-12 00:51:27.158,1931.0,2384.0,2079.0
162483,2013-12-12 00:51:27.177,1930.0,2382.0,2075.0
162484,2013-12-12 00:51:27.196,1924.0,2384.0,2077.0
162485,2013-12-12 00:51:27.215,1928.0,2383.0,2077.0
162486,2013-12-12 00:51:27.234,1930.0,2384.0,2077.0
162487,2013-12-12 00:51:27.253,1929.0,2386.0,2076.0
162488,2013-12-12 00:51:27.272,1928.0,2385.0,2077.0
162489,2013-12-12 00:51:27.291,1925.0,2383.0,2079.0
162490,2013-12-12 00:51:27.310,1931.0,2386.0,2073.0
162491,2013-12-12 00:51:27.329,1931.0,2383.0,2076.0
162492,2013-12-12 00:51:27.348,1927.0,2383.0,2079.0
162493,2013-12-12 00:51:27.367,1931.0,2388.0,2076.0
162494,2013-12-12 00:51:27.386,1932.0,2383.0,2072.0
162495,2013-12-12 00:51:27.405,1931.0,2386.0,2073.0
162496,2013-12-12 00:51:27.424,1926.0,2382.0,2072.0
162497,2013-12-12 00:51:27.443,1927.0,2388.0,2074.0
162498,2013-12-12 00:51:27.462,1930.0,2383.0,2074.0
162499,2013-12-12 00:51:27.481,1929.0,2385.0,2076.0
162500,2013-12-12 00:51:27.500,1926.0,2385.0,2078.0

In [7]:
a.to_csv('1_new1.csv',index = False , sep= ',')